module EventsHelper

    def sj_categories
        [
            ['Celebrate Diversity', 'Celebrate Diversity'],
            ['LGBTQ Rights', 'LGBTQ Rights'],
            ['Pride', 'Pride'],
            ['Black Lives Matter', 'Black Lives Matter'],
            ['Equality', 'Equality'],
            ['Civil Rights', 'Civil Rights'],
            ['Human Rights', 'Human Rights'],
            ['Citizenship', 'Citizenship'],
            ['Refugee Rights', 'Refugee Rights'],
            ['DACA', 'DACA'],
            ['Migrant Worker Rights', 'Migrant Worker Rights'],
            ['Labor Exploitation', 'Labor Exploitation'],
            ['Injustice At The Border', 'Injustice At The Border'],
            ['Families Belong Together', 'Families Belong Together'],
            ['Climate Change', 'Climate Change'],
            ['VOTE!', 'VOTE!'],
            ['Voting Rights', 'Voting Rights'],
            ['Womens Rights', 'Womens Rights'],
            ['Abortion Rights', 'Abortion Rights'],
            ['Me Too', 'Me Too'],
            ['Healthcare', 'Healthcare'],
            ['Ageism', 'Ageism'],
            ['Gender', 'Gender'],
            ['Gun Violence', 'Gun Violence'],
            ['Child Welfare', 'Child Welfare'],
            ['Education', 'Education'],
            ['Teacher Salaries', 'Teacher Salaries'],
            ['Abuse', 'Abuse'],
            ['Domestic Violence', 'Domestic Violence'],
            ['Economic Reform', 'Economic Reform'],
            ['Poverty & Economic Justice', 'Poverty & Economic Justice'],
            ['Power To The People', 'Power To The People'],
            ['Prison Reform', 'Prison Reform'],
            ['Systemic Oppression', 'Systemic Oppression'],
            ['Mental Health', 'Mental Health'],
            ['March For Science', 'March For Science'],
            ['Impeach The President', 'Impeach The President']
        ]
    end

    def us_states
        [
            ['CO', 'CO'],
            ['AK', 'AK'],
            ['AL', 'AL'],
            ['AR', 'AR'],
            ['AZ', 'AZ'],
            ['CA', 'CA'],
            ['CO', 'CO'],
            ['CT', 'CT'],
            ['DC', 'DC'],
            ['DE', 'DE'],
            ['FL', 'FL'],
            ['GA', 'GA'],
            ['HI', 'HI'],
            ['IA', 'IA'],
            ['ID', 'ID'],
            ['IL', 'IL'],
            ['IN', 'IN'],
            ['KS', 'KS'],
            ['KY', 'KY'],
            ['LA', 'LA'],
            ['MA', 'MA'],
            ['MD', 'MD'],
            ['ME', 'ME'],
            ['MI', 'MI'],
            ['MN', 'MN'],
            ['MO', 'MO'],
            ['MS', 'MS'],
            ['MT', 'MT'],
            ['NC', 'NC'],
            ['ND', 'ND'],
            ['NE', 'NE'],
            ['NH', 'NH'],
            ['NJ', 'NJ'],
            ['NM', 'NM'],
            ['NV', 'NV'],
            ['NY', 'NY'],
            ['OH', 'OH'],
            ['OK', 'OK'],
            ['OR', 'OR'],
            ['PA', 'PA'],
            ['RI', 'RI'],
            ['SC', 'SC'],
            ['SD', 'SD'],
            ['TN', 'TN'],
            ['TX', 'TX'],
            ['UT', 'UT'],
            ['VA', 'VA'],
            ['VT', 'VT'],
            ['WA', 'WA'],
            ['WI', 'WI'],
            ['WV', 'WV'],
            ['WY', 'WY']
        ]
    end

end
